[config]
version_check = false

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-step", "100", "--transition-fps", "120", "--transition-type", "grow", "--transition-angle", "30", "--transition-duration", "1"]

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland/colors.conf'
output_path = '~/.config/hypr/hyprland/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/fuzzel.ini'
output_path = '~/.config/fuzzel/fuzzel.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.ags_source_view]
input_path = '~/.config/matugen/templates/ags/sourceviewtheme.xml'
output_path = '~/.config/ags/assets/themes/sourceviewtheme.xml'

[templates.ags_source_view_light]
input_path = '~/.config/matugen/templates/ags/sourceviewtheme-light.xml'
output_path = '~/.config/ags/assets/themes/sourceviewtheme-light.xml'

